### ISSUE TITLE
Soft freezes when minimized.

### ISSUE THREAD

**Issue by Barthorgg** [Llop1s/FTP-PSVita-VPK-Installer#2]
When installing a big .vpk, minimizing the soft causes it to malfunction. data isn't transfered anymore, and it stays minimized, you cannot make it show up. Using Windows 10 for latest version of the soft.

**Comment by Mored1984** [comment]
Same issue, can't move the windows or minimize (freeze).

Note: using Windows 10 (x64)

**Comment by Llop1s** [comment]
Fixed in the new 3.0 version.
